BUILDNAME = Drunken Moose

SRCFILES = $(shell find kernel -name "*.c")
HDRFILES = $(shell find kernel -name "*.h")
ASMFILES = $(shell find kernel -name "*.s")

DRVFILES = $(shell find driver -name "*.c")

OBJFILES = $(patsubst kernel/%.c,build/objs/kernel/%.o,$(SRCFILES))
ASMOBJS  = $(patsubst kernel/%.s,build/objs/kernel/%.s.o,$(ASMFILES))

DRVOBJS  = $(patsubst driver/%.c,build/objs/driver/%.o,$(DRVFILES))

INCLUDE_DIRS = -Ikernel/include -Ishare/include \
               -Ilib/libc/includes -Ilib/libc/internals \
               -Ilib/libutil/include
               
AUTO_GENERATED = build/dump.txt build/linkmap.txt               
               
ASM = nasm
ASMFLAGS = -felf

OPTIMIZATION = -O1

CFLAGS_ALL = -std=gnu99 -Wall -static $(OPTIMIZATION) -g -ffreestanding -nostdlib\
              -nostartfiles -nodefaultlibs -fno-builtin $(INCLUDE_DIRS)

CC = i586-elf-gcc
CFLAGS = $(CFLAGS_ALL) -DKERNEL
         
DRIVER_FLAGS = $(CFLAGS_ALL) -DDRIVER -Idriver/include      
         
LD = i586-elf-ld
LDFLAGS = -Llib -static -Tbuild/scripts/kernel.ld

LIBS = -lutil -lc -lgcc

LUA = lua.exe

.PHONY: clean partclean todo run iso prepare driver

all: kernel

kernel: build/kos.sys build/dump.txt

iso:
	@build/scripts/cpyfiles.sh iso
	@build/scripts/makeiso.sh
	
run:
	@build/scripts/run.sh
	
dbg:
	@build/scripts/run.sh debug
	
debug:
	@bochsdbg.exe -f build/scripts/bochsdbg.rc
	
todo:
	@grep -e TODO -e FIXME $(SRCFILES)

prepare:
	@$(LUA) build/scripts/dirs.lua prep

build/kos.sys: $(OBJFILES) $(ASMOBJS) $(DRVOBJS)
	@$(LD) $(LDFLAGS) -obuild/kos.sys $(ASMOBJS) $(OBJFILES) $(DRVOBJS) $(LIBS) -Map build/linkmap.txt
	
build/dump.txt: build/kos.sys
	@objdump -d build/kos.sys > build/dump.txt
	
build/.rules: $(SRCFILES) Makefile
	@rm -f build/.rules
	@$(foreach file,$(SRCFILES),\
	echo -n $(subst kernel,build/objs/kernel,$(dir $(file))) >> build/.rules;\
	$(CC) $(CFLAGS) -MM $(file) >> build/.rules;\
	echo "	@$(CC) $(CFLAGS) -o$(patsubst kernel/%.c,build/objs/kernel/%.o,$(file)) -c $(file)" >> build/.rules;\
	)
	@$(foreach file,$(DRVFILES),\
	echo -n $(subst driver,build/objs/driver,$(dir $(file))) >> build/.rules;\
	$(CC) $(CFLAGS) -MM $(file) >> build/.rules;\
	echo "	@$(CC) $(DRIVER_FLAGS) -o$(patsubst driver/%.c,build/objs/driver/%.o,$(file)) -c $(file)" >> build/.rules;\
	)
	@$(foreach file,$(ASMFILES),\
	echo "$(patsubst kernel/%.s,build/objs/kernel/%.s.o,$(file)): $(file)" >> build/.rules;\
	echo "	@$(ASM) $(ASMFLAGS) -o$(patsubst kernel/%.s,build/objs/kernel/%.s.o,$(file)) $(file)" >> build/.rules;\
	)

-include build/.rules

clean: partclean
	@$(LUA) build/scripts/dirs.lua clean
	@rm -f build/.rules
	@rm -rf build/tmp
	@rm -f $(AUTOGENERATED)
	
partclean:
	@rm -f $(OBJFILES) $(ASMOBJS)
	
trouble:
	@echo Lua: $(LUA)
	@echo Object files:
	@echo $(OBJFILES)
	@echo ================
	@echo Driver Objects:
	@echo $(DRVOBJS)
	@echo ================
	@echo Rules:
	@cat  build/.rules
	